# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  source_enviroment:
    description: 'Source environment (e.g. staging)'
    required: true
  target_enviroment:
    description: 'Target environment (e.g. production)'
    required: true
  prefix_folder:
    description: 'Prefix for folder in which environment is stored(e.g. environments)'
    required: true
    default: 'environments'
  suffix_folder:
    description: 'Suffix for folder in which environment is stored(e.g. app)'
    required: true
    default: 'app'
  secrets_promotion:
    description: 'Option to promote secret(e.g. false)'
    required: true
    default: 'false'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/propagate_files.sh ${{ inputs.source_enviroment }} ${{ inputs.target_enviroment }} ${{ inputs.prefix_folder }} ${{ inputs.suffix_folder }} ${{ inputs.secrets_promotion }}
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Automatic ${{ inputs.source_enviroment }} to ${{ inputs.target_enviroment }} propagation
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: ${{ inputs.source_enviroment }}-to-${{ inputs.target_enviroment }}-propagation
        delete-branch: true
        title: '[${{ inputs.target_enviroment }}] ${{ inputs.source_enviroment }} to ${{ inputs.target_enviroment }} propagation'
        body: |
          Update of manifest files. Please check if there are any changes in the <environment>-values.yaml specific file.
        labels: |
          propagation
          ${{ inputs.target_enviroment }}
        draft: false
